### ISSUE TITLE
yara compile errors in lauching scripts

### ISSUE THREAD

**Issue by polosec** [c0m4r/Loki-daemonized#10]
**Describe the bug**
errors in compiling yara rules when run the main script.
**To Reproduce**
command:`./paranoya.py -d -s 20000 --noindicator --csv  --intense --logfolder log --silent  --nolisten `

```

File "/Users/1/Downloads/paranoya-4.0.0/./paranoya.py", line 1277, in initialize_yara_rules
    compiled_rules = yara.compile(
yara.SyntaxError: line 21: invalid field name "number_of_signatures"
yara.SyntaxError: line 112: invalid field name "imphash"


```
**Screenshots**
<img width="886" alt="image" src="https://github.com/c0m4r/paranoya/assets/34666152/2a06af5b-1c1c-4e95-9a85-99afbedc3b67">
**Your environment (please complete the following information):**
 - CPU arch: aarch64
 - Python version: 3.10
 - Env: venv
 - Container: none
 - Terminal  terminal default(mac)
 - paranoya version 4.0.0

**Comment by c0m4r** [comment]
Hi, first of all - paranoya doesn't support mac and I do not plan such support. Therefore, I cannot reproduce the error. However a quick google search suggested that these errors might occur on MacOS due to some openssl-related issues:

- https://medium.com/@baglai.vlad/installing-yara-with-crypto-on-macos-80b7dd16b0b8
- https://github.com/VirusTotal/yara/issues/378
- https://github.com/VirusTotal/yara-python/issues/119

I hope you can sort it out with these read. You can also try the docker version of paranoya.
